// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBewertung(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddBewertung'](arg1, arg2, arg3, arg4);
}

export function ExportBewertungen(arg1) {
  return window['go']['main']['App']['ExportBewertungen'](arg1);
}

export function GetBewertungen() {
  return window['go']['main']['App']['GetBewertungen']();
}

export function GetMaxPunkte() {
  return window['go']['main']['App']['GetMaxPunkte']();
}

export function GetNotenspiegel() {
  return window['go']['main']['App']['GetNotenspiegel']();
}

export function OpenSaveDialog() {
  return window['go']['main']['App']['OpenSaveDialog']();
}

export function SetMaxPunkte(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetMaxPunkte'](arg1, arg2, arg3, arg4);
}

export function ToggleWertung(arg1) {
  return window['go']['main']['App']['ToggleWertung'](arg1);
}
