// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBewertung(arg1:string,arg2:string,arg3:number,arg4:number):Promise<boolean>;

export function ExportBewertungen(arg1:string):Promise<void>;

export function GetBewertungen():Promise<Array<main.Bewertung>>;

export function GetMaxPunkte():Promise<main.MaxPunkte>;

export function GetNotenspiegel():Promise<{[key: number]: number}>;

export function OpenSaveDialog():Promise<string>;

export function SetMaxPunkte(arg1:number,arg2:number,arg3:number,arg4:number):Promise<boolean>;

export function ToggleWertung(arg1:number):Promise<main.Bewertung>;
