name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write  # Wichtig für Release-Uploads

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'grades-management-app'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'grades-management-app'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'grades-management-app'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.23'
          github_token: ${{ github.token }}  # Explizit Token übergeben

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
